//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ergenekon.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ergenekon.Infrastructure.Localization.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayın {0},.
        /// </summary>
        public static string EmailChanged_Body1 {
            get {
                return ResourceManager.GetString("EmailChanged_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresin &lt;strong&gt;{0}&lt;/strong&gt; iken &lt;strong&gt;{1}&lt;/strong&gt; olarak değiştirildi..
        /// </summary>
        public static string EmailChanged_Body2 {
            get {
                return ResourceManager.GetString("EmailChanged_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğer bu işlemi siz yapmadıysanız ya da yetkisiz bir kişinin hesabınıza eriştiğini düşünüyorsanız en kısa sürede &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt; hesap bilgilerim sayfanızı ziyaret ederek parolanızı değiştirmelisiniz..
        /// </summary>
        public static string EmailChanged_Body3 {
            get {
                return ResourceManager.GetString("EmailChanged_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan işlemi geri almak için ise aşağıdaki bağlantıya tıklayarak geri alabilirsiniz..
        /// </summary>
        public static string EmailChanged_Body4 {
            get {
                return ResourceManager.GetString("EmailChanged_Body4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        public static string EmailChanged_Body5 {
            get {
                return ResourceManager.GetString("EmailChanged_Body5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresin değişti.
        /// </summary>
        public static string EmailChanged_Subject {
            get {
                return ResourceManager.GetString("EmailChanged_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayın {0},.
        /// </summary>
        public static string EmailChangeRequest_Body1 {
            get {
                return ResourceManager.GetString("EmailChangeRequest_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresinizi değiştirebilmek için aşağıdaki bağlantıya tıklamanız gerekmektedir..
        /// </summary>
        public static string EmailChangeRequest_Body2 {
            get {
                return ResourceManager.GetString("EmailChangeRequest_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        public static string EmailChangeRequest_Body3 {
            get {
                return ResourceManager.GetString("EmailChangeRequest_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay bağlantıları iki gün sonra zaman aşımına uğrar..
        /// </summary>
        public static string EmailChangeRequest_Body4 {
            get {
                return ResourceManager.GetString("EmailChangeRequest_Body4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresi değişikliği.
        /// </summary>
        public static string EmailChangeRequest_Subject {
            get {
                return ResourceManager.GetString("EmailChangeRequest_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayın {0},.
        /// </summary>
        public static string EmailConfirmation_Body1 {
            get {
                return ResourceManager.GetString("EmailConfirmation_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresinizi onaylamak için onay kodunu girmeniz ya da aşağıdaki bağlantıya tıklamanız gerekmektedir..
        /// </summary>
        public static string EmailConfirmation_Body2 {
            get {
                return ResourceManager.GetString("EmailConfirmation_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;{0}&lt;/h1&gt;.
        /// </summary>
        public static string EmailConfirmation_Body3_Code {
            get {
                return ResourceManager.GetString("EmailConfirmation_Body3_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        public static string EmailConfirmation_Body3_Link {
            get {
                return ResourceManager.GetString("EmailConfirmation_Body3_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay bağlantıları iki gün sonra zaman aşımına uğrar..
        /// </summary>
        public static string EmailConfirmation_Body4 {
            get {
                return ResourceManager.GetString("EmailConfirmation_Body4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldin! E-posta onay kodun: {0}.
        /// </summary>
        public static string EmailConfirmation_SubjectCode {
            get {
                return ResourceManager.GetString("EmailConfirmation_SubjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş geldin! E-posta adresini onayla.
        /// </summary>
        public static string EmailConfirmation_SubjectLink {
            get {
                return ResourceManager.GetString("EmailConfirmation_SubjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ileti, hesabınız ve hizmetlerinizdeki önemli değişiklikler hakkında bilgilendirmek için gönderilmiştir..
        /// </summary>
        public static string FooterInfo {
            get {
                return ResourceManager.GetString("FooterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saygılarımızla,&lt;br/&gt;Maydere.
        /// </summary>
        public static string FooterSignature {
            get {
                return ResourceManager.GetString("FooterSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayın {0},.
        /// </summary>
        public static string PasswordRecovery_Body1 {
            get {
                return ResourceManager.GetString("PasswordRecovery_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınıza ait parolanızı sıfırlamak için aşağıdaki bağlantıya tıklamanız gerekmektedir..
        /// </summary>
        public static string PasswordRecovery_Body2 {
            get {
                return ResourceManager.GetString("PasswordRecovery_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;.
        /// </summary>
        public static string PasswordRecovery_Body3 {
            get {
                return ResourceManager.GetString("PasswordRecovery_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola sıfırlamak için herhangi bir istekte bulunmadıysanız bu iletiyi yok sayabilirsiniz..
        /// </summary>
        public static string PasswordRecovery_Body4 {
            get {
                return ResourceManager.GetString("PasswordRecovery_Body4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay bağlantıları iki gün sonra zaman aşımına uğrar..
        /// </summary>
        public static string PasswordRecovery_Body5 {
            get {
                return ResourceManager.GetString("PasswordRecovery_Body5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola sıfırlama isteği.
        /// </summary>
        public static string PasswordRecovery_Subject {
            get {
                return ResourceManager.GetString("PasswordRecovery_Subject", resourceCulture);
            }
        }
    }
}
